<a href="https://colab.research.google.com/github/V-Nayak/ML/blob/main/Ensembling_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv("/content/drive/MyDrive/ML Projects/seeds.csv")

In [3]:
df

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0    15.26      14.84       0.8710          5.763         3.312   
1    14.88      14.57       0.8811          5.554         3.333   
2    14.29      14.09       0.9050          5.291         3.337   
3    13.84      13.94       0.8955          5.324         3.379   
4    16.14      14.99       0.9034          5.658         3.562   
..     ...        ...          ...            ...           ...   
194  12.19      13.20       0.8783          5.137         2.981   
195  11.23      12.88       0.8511          5.140         2.795   
196  13.20      13.66       0.8883          5.236         3.232   
197  11.84      13.21       0.8521          5.175         2.836   
198  12.30      13.34       0.8684          5.243         2.974   

     Asymmetry.Coeff  Kernel.Groove  Type  
0              2.221          5.220     1  
1              1.018          4.956     1  
2              2.699          4.825     1  
3              2.259          4.805     1  
4              1.355          5.175     1  
..               ...            ...   ...  
194            3.631          4.870     3  
195            4.325          5.003     3  
196            8.315          5.056     3  
197            3.598          5.044     3  
198            5.637          5.063     3  

[199 rows x 8 columns]

In [4]:
df.describe()


Area   Perimeter  Compactness  Kernel.Length  Kernel.Width  \
count  199.000000  199.000000   199.000000     199.000000    199.000000   
mean    14.918744   14.595829     0.870811       5.643151      3.265533   
std      2.919976    1.310445     0.023320       0.443593      0.378322   
min     10.590000   12.410000     0.808100       4.899000      2.630000   
25%     12.330000   13.470000     0.857100       5.267000      2.954500   
50%     14.430000   14.370000     0.873400       5.541000      3.245000   
75%     17.455000   15.805000     0.886800       6.002000      3.564500   
max     21.180000   17.250000     0.918300       6.675000      4.033000   

       Asymmetry.Coeff  Kernel.Groove        Type  
count       199.000000     199.000000  199.000000  
mean          3.699217       5.420653    1.994975  
std           1.471102       0.492718    0.813382  
min           0.765100       4.519000    1.000000  
25%           2.570000       5.046000    1.000000  
50%           3.631000       5.228000    2.000000  
75%           4.799000       5.879000    3.000000  
max           8.315000       6.550000    3.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             199 non-null    float64
 1   Perimeter        199 non-null    float64
 2   Compactness      199 non-null    float64
 3   Kernel.Length    199 non-null    float64
 4   Kernel.Width     199 non-null    float64
 5   Asymmetry.Coeff  199 non-null    float64
 6   Kernel.Groove    199 non-null    float64
 7   Type             199 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 12.6 KB


In [6]:
#checking the null values in the table
df.isnull().sum()

Area               0
Perimeter          0
Compactness        0
Kernel.Length      0
Kernel.Width       0
Asymmetry.Coeff    0
Kernel.Groove      0
Type               0
dtype: int64

# Dividing the cadidates in Train and Test

In [7]:
# input
X = df.iloc[:, :-1]

#output
Y = df.iloc[:, -1]

In [16]:
# Splitting between train data into training and validation dataset
x_train, x_test, y_train, y_test = train_test_split(
 df.iloc[:, :-1], df.iloc[:, -1],
	test_size = 0.20)

print("Train data shape of X = % s and Y = % s : "%(
	x_train.shape, y_train.shape))

print("Test data shape of X = % s and Y = % s : "%(
	x_test.shape, y_test.shape))

Train data shape of X = (159, 7) and Y = (159,) : 
Test data shape of X = (40, 7) and Y = (40,) : 


## **Max Voting technique**

In [18]:
from sklearn import tree
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

model1=LogisticRegression(random_state=1)
model2=tree.DecisionTreeClassifier(random_state=1)

# Making the final model using voting classifie
model=VotingClassifier(estimators=[('lr',model1),('dt',model2)],voting='hard')

#training all the model on the train dataset
model.fit(x_train,y_train)

## predicting the output on the test dataset
# pred_final = final_model.predict(x_test)

Mod_SR= model.score(x_test,y_test)

print('Model Score is:', Mod_SR)



Model Score is: 0.975


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


## **Averaging technique**

In [19]:
from sklearn.neighbors  import KNeighborsClassifier

model1=tree.DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()

model1.fit(x_train, y_train)
model2.fit(x_train, y_train)
model3.fit(x_train, y_train)

pred1=model1.predict_proba(x_test)
pred2=model2.predict_proba(x_test)
pred3=model3.predict_proba(x_test)

finalpred=(pred1+pred2+pred3)/3

print('Model Score is:',finalpred)

 


Model Score is: [[1.77905612e-02 6.88817316e-05 9.82140557e-01]
 [2.08502454e-02 9.79062023e-01 8.77312519e-05]
 [8.02850941e-01 1.94020535e-01 3.12852415e-03]
 [9.94039428e-01 1.40014249e-03 4.56042901e-03]
 [4.28885165e-01 1.77952516e-04 5.70936883e-01]
 [2.37893927e-02 9.21636954e-06 9.76201391e-01]
 [9.84033055e-01 5.15205428e-03 1.08148905e-02]
 [2.38253727e-03 1.93266857e-06 9.97615530e-01]
 [9.94456484e-01 5.22510849e-03 3.18407840e-04]
 [6.33062800e-04 9.99365104e-01 1.83321880e-06]
 [7.26640622e-03 1.83030541e-05 9.92715291e-01]
 [6.84997526e-05 9.99931497e-01 3.17358976e-09]
 [1.62757312e-01 8.35521732e-01 1.72095655e-03]
 [9.62041444e-01 3.61467813e-03 3.43438774e-02]
 [9.79886884e-01 2.46347471e-03 1.76496410e-02]
 [9.23895454e-01 2.46226704e-04 7.58583188e-02]
 [9.79258929e-01 2.06011038e-03 1.86809603e-02]
 [1.39789594e-04 9.99860147e-01 6.35042259e-08]
 [6.20023224e-02 8.17956228e-05 9.37915882e-01]
 [9.25887340e-01 6.91146862e-04 7.34215135e-02]
 [1.08433658e-02 9.89112

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


## **Weighted Average**

In [20]:
finalpred=(pred1*0.3+pred2*0.3+pred3*0.4)/3

print('Model value is:',finalpred)

Model value is: [[7.11622446e-03 2.75526926e-05 3.26189556e-01]
 [8.34009816e-03 3.24958143e-01 3.50925008e-05]
 [2.67807043e-01 6.42748807e-02 1.25140966e-03]
 [3.30949105e-01 5.60056998e-04 1.82417160e-03]
 [1.51554066e-01 7.11810064e-05 1.81708086e-01]
 [9.51575710e-03 3.68654782e-06 3.23813890e-01]
 [3.26946555e-01 2.06082171e-03 4.32595619e-03]
 [9.53014908e-04 7.73067428e-07 3.32379545e-01]
 [3.31115927e-01 2.09004340e-03 1.27363136e-04]
 [2.53225120e-04 3.33079375e-01 7.33287519e-07]
 [2.90656249e-03 7.32122164e-06 3.30419450e-01]
 [2.73999010e-05 3.33305932e-01 1.26943590e-09]
 [5.84362579e-02 2.74208693e-01 6.88382619e-04]
 [3.18149911e-01 1.44587125e-03 1.37375510e-02]
 [3.25288087e-01 9.85389882e-04 7.05985641e-03]
 [3.09558182e-01 9.84906817e-05 2.36766609e-02]
 [3.25036905e-01 8.24044153e-04 7.47238413e-03]
 [5.59158374e-05 3.33277392e-01 2.54016904e-08]
 [2.48009290e-02 3.27182491e-05 3.08499686e-01]
 [3.10354936e-01 2.76458745e-04 2.27019387e-02]
 [4.33734631e-03 3.28978